sudo: true
language: nix

matrix:
  include:
  - env: GHC_VERSION="ghc822"
  - env: GHC_VERSION="ghc842"
  - env: GHC_VERSION="ghcHEAD"

  allowed_failures:
  - env: GHC_VERSION="ghcHEAD"

script:
  - nix-build --argstr compiler $GHC_VERSION
